apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wooco-spring

resources:
  - ../../base
  - deployment.yaml
  - service.yaml
  - http-route.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: prod
